name: Stress testing with JMeter

on:  
  workflow_dispatch:
 # repository_dispatch:
 #   types: [load-test-image]

jobs:
  load-test-with-jmeter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install postman to jmeter converter
   #     run: | 
   #       npm install -s postman-jmeter
        run: npm install
      - name: install jmeter
        run: |
          java -version
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.5.zip
          unzip apache-jmeter-5.5.zip
          cd apache-jmeter-5.5/bin
          ./jmeter -v
          pwd
      - name: Convert postman collection
        run: | 
          node ./bin/convert-postman-jmeter -p ./test/catfact-coll.json -j catfacts.jmx -o -v=resolve

      - name: Run Stress Tests
        run: |
          cd ./apache-jmeter-5.5/bin 
          ./jmeter -n -t ${{ github.workspace }}/catfacts.jmx -l ${{ github.workspace }}/results.csv -e -o ${{ github.workspace }}/output
      - name: Create Date Stamp
        run: |
          d=$( echo "$(date +'%Y%m%d%H%M%S')")
          echo "DATE_STAMP=$( echo $d)" >> $GITHUB_ENV
      - name: Screenshot Test
        run: |
          npm install --global capture-website-cli
          capture-website output/index.html --output=screenshot_${{ env.DATE_STAMP }}.png
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-load-test-image
          path: screenshot_${{ env.GITHUB_RUN_ID }}.png
      - name:  Add image to repo
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git status
          mkdir -p assets/images/
          mv screenshot_${{ env.GITHUB_RUN_ID }}.png assets/images/
          git add assets/images/screenshot_${{ env.GITHUB_RUN_ID }}.png
          git commit -m "added assets/images/screenshot_${{ env.GITHUB_RUN_ID }}.png"
          git push
          git status
          echo "https://github.com/${{github.repository}}/blob/main/assets/images/screenshot_${{ env.GITHUB_RUN_ID }}.png?raw=true"
      - name: Send results to postman
        run: | 
          node ./bin/respond -w  774fda03-bf0a-4c99-b915-b7ecf1856162 -u https://github.com/postman-solutions-eng/postman-jmeter/blob/main/assets/images/screenshot_${{ env.DATE_STAMP }}.png -k ${{ secrets.POSTMAN_API_KEY }}

          
          
          
