name: Stress testing with JMeter and Image

on:  
  workflow_dispatch:
  repository_dispatch:
    types: [load-test-image]

jobs:
  load-test-with-jmeter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install postman to jmeter converter
   #     run: | 
   #       npm install -s postman-jmeter
        run: npm install
      - name: install jmeter
        run: |
          java -version
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.5.zip
          unzip apache-jmeter-5.5.zip
          cd apache-jmeter-5.5/bin
          ./jmeter -v
          pwd
      - name: Convert postman collection
        run: | 
          node ./bin/convert-postman-jmeter -p ./test/catfact-coll.json -j catfacts.jmx -o -v=resolve
      - name: Run Stress Tests
        run: |
          cd ./apache-jmeter-5.5/bin 
          ./jmeter -n -t ${{ github.workspace }}/catfacts.jmx -l ${{ github.workspace }}/results.csv -e -o ${{ github.workspace }}/output
      - name: Create Date Stamp
        run: |
          d=$( echo "$(date +'%Y%m%d%H%M%S')")
          echo "DATE_STAMP=$( echo $d)" >> $GITHUB_ENV
      - name: Screenshot Test
        run: |
          npm install --global capture-website-cli
          capture-website output/index.html --output=screenshot_${{ env.DATE_STAMP }}.png          
          
