name: JMeter trigger

on:  
  workflow_dispatch:
    inputs:
      workspaceID:
        description: 'ID of the workspace to send results to'
        required: true
        # default: 'warning'
        type: string
      variableStrategy:
        description: 'Resolve variable values, or transform to JMeter syntax'
        required: false
        default: 'resolve'
        type: choice
        options:
        - resolve
        - transform
      collectionPath:
        description: 'Path in repo to collection to test'
        required: true
        type: string
        default: './examples/catfact-coll.json'
      envFile:
        description: 'Exported Postman environment file'
        required: false
        type: string
        default: " "
        
  
jobs:
  load-test-with-jmeter:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        run: | 
          curl -X POST https://api.github.com/repos/postman-solutions-eng/postman-jmeter/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.GH_PAT }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "workspaceID": "${{ inputs.workspaceID }}", "variableStrategy": "${{ inputs.variableStrategy }}","collectionPath":"${{ inputs.collectionPath }}", "envFile": "${{ inputs.envFile }}" }}'
      